[wokwi]
version = 1
firmware = ".pio/build/esp32doit-devkit-v1/firmware.bin"
elf = ".pio/build/esp32doit-devkit-v1/firmware.elf"

[workspace]
version = 1

[esp32]
chip = "ESP32"

[[net]]
ssid = "Wokwi-GUEST"
password = ""

[[components]]
id = "DHTesp"